stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - package

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - ./mvnw.cmd compiler:compile
    - ./mvnw.cmd compiler:testCompile
  artifacts:
    paths:
      - target/classes/
      - target/test-classes/

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - ./mvnw.cmd surefire:test
  dependencies:
    - build-job
 
package-job:      # This job runs in the package stage.
  stage: package  # It only runs when both jobs in the test stage complete successfully.
  script:
    - ./mvnw.cmd jar:jar
  dependencies:
    - build-job
